# Generated by Django 2.1.4 on 2019-01-10 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='jobfiles',
            new_name='jobfile',
        ),
    ]
